version: '3.8'

services:
  tarefas_database:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: tarefas
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
